# Generated by Django 6.0.1 on 2026-01-17 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_level', models.CharField(blank=True, max_length=50, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('clinical_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_method', models.CharField(blank=True, max_length=50, null=True)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('test_score', models.FloatField(default=0.0)),
                ('calibrated_level', models.CharField(default='Novice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
