# Generated by Django 6.0.1 on 2026-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='language',
            field=models.CharField(default='fr', max_length=10, verbose_name='Langue préférée'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='pending_test_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
