# Generated by Django 6.0.1 on 2026-01-17 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specialty', models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Pneumologie', 'Pneumologie'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Neurologie', 'Neurologie'), ('Urgence', 'Urgence')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Novice', 'Novice'), ('Intermédiaire', 'Intermédiaire'), ('Expert', 'Expert')], default='Novice', max_length=20)),
                ('case_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
