# Generated by Django 6.0.1 on 2026-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcase',
            name='specialty',
            field=models.CharField(choices=[('Médecine Générale', 'Médecine Générale'), ('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Pédiatrie', 'Pédiatrie'), ('Neurologie', 'Neurologie'), ('Orthopédie', 'Orthopédie'), ('Psychiatrie', 'Psychiatrie'), ('Radiologie', 'Radiologie'), ('Chirurgie', 'Chirurgie'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Urgence', 'Urgence'), ('Infectiologie', 'Infectiologie'), ('Endocrinologie', 'Endocrinologie')], default='Médecine Générale', max_length=50),
        ),
    ]
